# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_images', models.TextField(null=True)),
                ('shop_title', models.TextField(null=True)),
                ('user_type', models.TextField(null=True)),
                ('zk_final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('title', models.TextField(null=True)),
                ('nick', models.TextField(null=True)),
                ('seller_id', models.BigIntegerField(null=True)),
                ('volume', models.TextField(null=True)),
                ('pict_url', models.TextField(null=True)),
                ('item_url', models.TextField(null=True)),
                ('coupon_total_count', models.TextField(null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('coupon_info', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('num_iid', models.BigIntegerField(null=True)),
                ('coupon_remain_count', models.TextField(null=True)),
                ('coupon_start_time', models.TextField(null=True)),
                ('coupon_end_time', models.TextField(null=True)),
                ('coupon_click_url', models.TextField(null=True)),
                ('item_description', models.TextField(null=True)),
                ('employ', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(null=True)),
                ('userPwd', models.TextField(null=True)),
            ],
        ),
    ]
